# Drop_out_Regularization

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

In [3]:
import warnings

In [4]:
warnings.filterwarnings('ignore')

In [10]:
df=pd.read_csv('sonar.csv',header=None)

In [11]:
df.sample(5)

0       1       2       3       4       5       6       7       8   \
111  0.0530  0.0885  0.1997  0.2604  0.3225  0.2247  0.0617  0.2287  0.0950   
118  0.0363  0.0478  0.0298  0.0210  0.1409  0.1916  0.1349  0.1613  0.1703   
77   0.0336  0.0294  0.0476  0.0539  0.0794  0.0804  0.1136  0.1228  0.1235   
75   0.0202  0.0104  0.0325  0.0239  0.0807  0.1529  0.1154  0.0608  0.1317   
176  0.0635  0.0709  0.0453  0.0333  0.0185  0.1260  0.1015  0.1918  0.3362   

         9   ...      51      52      53      54      55      56      57  \
111  0.0740  ...  0.0244  0.0199  0.0257  0.0082  0.0151  0.0171  0.0146   
118  0.1444  ...  0.0115  0.0190  0.0055  0.0096  0.0050  0.0066  0.0114   
77   0.0842  ...  0.0150  0.0111  0.0032  0.0035  0.0169  0.0137  0.0015   
75   0.1370  ...  0.0127  0.0081  0.0067  0.0043  0.0065  0.0049  0.0054   
176  0.3900  ...  0.0048  0.0025  0.0087  0.0072  0.0095  0.0086  0.0085   

         58      59  60  
111  0.0134  0.0056   M  
118  0.0073  0.0033   M  
77   0.0069  0.0051   R  
75   0.0073  0.0054   R  
176  0.0040  0.0051   M  

[5 rows x 61 columns]

In [9]:
df.shape

(208, 61)

In [13]:
#None Value

In [14]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [15]:
#tackle None Value

In [17]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [18]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [19]:
#This is a binary classification m is a metal and R is a rock

In [20]:
X=df.drop(60,axis=1) #or axis='columns'
y=df[60]
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [21]:
X.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      50      51      52      53      54      55      56  \
0  0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   

       57      58      59  
0  0.0084  0.0090  0.0032  
1  0.0049  0.0052  0.0044  
2  0.0164  0.0095  0.0078  
3  0.0044  0.0040  0.0117  
4  0.0048  0.0107  0.0094  

[5 rows x 60 columns]

In [22]:
y=pd.get_dummies(y,drop_first=True)
y.sample(5)# R--->1 and M--->0

R
41   1
50   1
107  0
179  0
126  0

In [23]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

In [26]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=1)

In [27]:
X_train.shape,X_test.shape

((156, 60), (52, 60))

# Using Deep Learning Model

Model without Dropout Layer

In [28]:
import tensorflow as tf
from tensorflow import keras

In [83]:
model=keras.Sequential([
    keras.layers.Dense(60,input_dim=60,activation='relu'),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid'),

])


model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])

model.fit(X_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
20/20 [==============================] - 2s 1ms/step - loss: 0.6902 - accuracy: 0.5256
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6627 - accuracy: 0.5641
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6378 - accuracy: 0.7308
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6094 - accuracy: 0.7628
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5696 - accuracy: 0.7949
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5328 - accuracy: 0.7949
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4983 - accuracy: 0.8077
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5061 - accuracy: 0.7372
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4676 - accuracy: 0.7821
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4595 - accuracy: 0.8013
Epoch 11/

20/20 [==============================] - 0s 1ms/step - loss: 0.0064 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0055 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0055 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0050 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0050 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0048 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 93/100


In [84]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 3ms/step - loss: 1.2982 - accuracy: 0.7308


[1.2981646060943604, 0.7307692170143127]

In [49]:
# we can see the accuracy of our train model is 1, but the accuracy of test model is 0.76
#this is overfitting

In [85]:
y_pred=model.predict(X_test)

2/2 [==============================] - 0s 3ms/step


In [86]:
y_pred

array([[5.99522778e-08],
       [9.99243677e-01],
       [9.99390125e-01],
       [4.80670169e-05],
       [9.99999881e-01],
       [9.99978423e-01],
       [1.69853885e-02],
       [1.00000000e+00],
       [4.07811982e-04],
       [1.00000000e+00],
       [8.17498043e-02],
       [3.11172262e-05],
       [3.09225929e-04],
       [6.66790351e-04],
       [2.73223338e-03],
       [9.81383383e-01],
       [9.99940217e-01],
       [9.04498011e-05],
       [4.10220772e-02],
       [9.99999821e-01],
       [1.80916788e-04],
       [9.99999940e-01],
       [4.33003576e-03],
       [9.99997020e-01],
       [6.53864583e-03],
       [6.28000919e-07],
       [1.11198269e-01],
       [2.23527477e-05],
       [9.99999702e-01],
       [6.49946034e-01],
       [9.89094317e-01],
       [1.89158243e-06],
       [1.35577410e-01],
       [2.79418398e-02],
       [9.94619310e-01],
       [9.99818265e-01],
       [9.99999642e-01],
       [8.70902359e-01],
       [9.99992251e-01],
       [6.60130987e-04],


In [55]:
y_pred.shape

(52, 1)

In [87]:
y_pred=y_pred.reshape(-1)

In [88]:
y_pred.shape

(52,)

In [89]:
print(y_pred[:10])

[5.9952278e-08 9.9924368e-01 9.9939013e-01 4.8067017e-05 9.9999988e-01
 9.9997842e-01 1.6985388e-02 1.0000000e+00 4.0781198e-04 1.0000000e+00]


In [90]:
#Round the values to nearest integer 0 or 1
y_pred=np.round(y_pred)

In [91]:
print(y_pred[:10])

[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]


In [92]:
y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [93]:
from sklearn.metrics import confusion_matrix,classification_report

In [94]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.71      0.81      0.76        27
           1       0.76      0.64      0.70        25

    accuracy                           0.73        52
   macro avg       0.74      0.73      0.73        52
weighted avg       0.73      0.73      0.73        52



In [95]:
modelD=keras.Sequential([
    keras.layers.Dense(60,input_dim=60,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(1,activation='sigmoid'),

])


modelD.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])

modelD.fit(X_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.7004 - accuracy: 0.5449
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6918 - accuracy: 0.5577
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7139 - accuracy: 0.5192
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6854 - accuracy: 0.5513
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6957 - accuracy: 0.5385
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7083 - accuracy: 0.4808
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6870 - accuracy: 0.5449
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6698 - accuracy: 0.5705
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6392 - accuracy: 0.6603
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6561 - accuracy: 0.5769
Epoch 11/

20/20 [==============================] - 0s 2ms/step - loss: 0.2960 - accuracy: 0.8910
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2665 - accuracy: 0.9231
Epoch 85/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2737 - accuracy: 0.8910
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2595 - accuracy: 0.8782
Epoch 87/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2730 - accuracy: 0.8910
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2435 - accuracy: 0.8974
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2943 - accuracy: 0.8974
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2592 - accuracy: 0.8782
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2647 - accuracy: 0.8910
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2873 - accuracy: 0.8526
Epoch 93/100


In [96]:
modelD.evaluate(X_test,y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.5206 - accuracy: 0.7308


[0.520587682723999, 0.7307692170143127]

In [68]:
#we can see that with Dropout we reduce the difference between the accuracy of train and test

In [97]:
y_pred=modelD.predict(X_test)

2/2 [==============================] - 0s 2ms/step


In [98]:
y_pred=y_pred.reshape(-1)

In [99]:
y_pred=np.round(y_pred)

In [100]:
print(y_pred[:10])

[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]


In [101]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.71      0.81      0.76        27
           1       0.76      0.64      0.70        25

    accuracy                           0.73        52
   macro avg       0.74      0.73      0.73        52
weighted avg       0.73      0.73      0.73        52

