# Implement Mean Absolute Error

In [5]:
import numpy as np

In [6]:
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [7]:
#Mean absloute error

In [8]:
def mae(y_true,y_predicted):
    total_error=0
    for yt, yp in zip(y_true,y_predicted):
        print(yt,yp)
        total_error +=(abs(yt-yp))
    print("Total error is: ",total_error)
    mae=total_error/len(y_true)
    print("Mean Absolute Error is:",mae)
    return mae

In [9]:
mae(y_true,y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1
Total error is:  2.5
Mean Absolute Error is: 0.5


0.5

In [10]:
y_predicted-y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [11]:
abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [12]:
#mean error

In [13]:
np.mean(abs(y_predicted-y_true))

0.5

In [14]:
#total error

In [15]:
np.sum(abs(y_predicted-y_true))

2.5

In [16]:
#square error

In [17]:
np.sum(abs((y_predicted-y_true)**2))

1.83

In [18]:
#log loss-binary cross loss function

In [19]:
np.log([0])

C:\Users\HUAWEI\AppData\Local\Temp\ipykernel_11736\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [20]:
np.log([0.0000001])

array([-16.11809565])

In [21]:
epsilon=1e-15   # a value which is very close to zero

In [22]:
y_predicted

array([1, 1, 0, 0, 1])

In [23]:
y_predicted_new=[max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [ ]:
#we want to use 1-y_predicted to make value close to one but not 1

In [24]:
y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [25]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [26]:
np.log(y_predicted)

C:\Users\HUAWEI\AppData\Local\Temp\ipykernel_11736\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [28]:
y_predicted_new=np.array(y_predicted_new)

In [29]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [30]:
def log_loss(y_true,y_predicted,epsilon=1e-15):
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [31]:
log_loss(y_true,y_predicted)

17.269388197455342

Implement Mean Squared Error Function without using numpy

In [32]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [33]:
mse(y_true, y_predicted)

Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366

In [35]:
#By using numpy

In [36]:
np.mean(np.square(y_true-y_predicted))

0.366