# Matrix Basics

In [1]:
import numpy as np

In [3]:
revenue=np.array([[100,200,300],[400,500,600],[700,800,900]])
expenses=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [4]:
revenue.shape

(3, 3)

In [5]:
type(revenue)

numpy.ndarray

In [6]:
revenue.ndim

2

In [7]:
profit=revenue-expenses

In [8]:
profit

array([[ 90, 180, 270],
       [360, 450, 540],
       [630, 720, 810]])

In [9]:
price=np.array([1000,200,400])

In [10]:
units=np.array([[100,200,300],[400,500,600],[700,800,9000]])

In [11]:
price*units

array([[ 100000,   40000,  120000],
       [ 400000,  100000,  240000],
       [ 700000,  160000, 3600000]])

In [12]:
np.dot(price,units)

array([ 460000,  620000, 4020000])