# Introduction of Pytorch

In [1]:
import torch

Tensor is a number, vector, Matrix , any n Dimentional Array

In [4]:
#Number

In [5]:
t1=torch.tensor(4.0)
t1

tensor(4.)

In [6]:
t1.dtype

torch.float32

In [8]:
#Vector

In [12]:
t2=torch.tensor([1.0,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [13]:
t2.dtype

torch.float32

In [14]:
#Matrix

In [16]:
t3=torch.tensor([
    [1,2,3],
    [4,5,6]
])

t3

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
t3.dtype

torch.int64

In [19]:
t4=torch.tensor([
    [[1,2,3],
     [4,5,6]],
    [[1,2,3],
     [4,5,6]]
    ])
t4

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [20]:
t4.dtype

torch.int64

In [21]:
t1.ndim

0

In [22]:
t2.ndim

1

In [23]:
t3.ndim

2

In [24]:
t4.ndim

3

In [25]:
t1.shape

torch.Size([])

In [26]:
t2.shape

torch.Size([4])

In [27]:
t3.shape

torch.Size([2, 3])

In [29]:
t4.shape

torch.Size([2, 2, 3])

In [30]:
#Create Tensor

In [32]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [33]:
#Arithmetic Operation
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [34]:
#Pytorch automatically compute the derivative of y

In [35]:
#Compute Derivative
y.backward()

In [37]:
#Display Derivatives
print("dy/dx:",x.grad)
print("dy/dw:",w.grad)
print("dy/db:",b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [38]:
#x is None, because x does not have requires_grad set to True

Tensor Functions

In [39]:
t6=torch.full((2,3),10)

In [40]:
t6

tensor([[10, 10, 10],
        [10, 10, 10]])

In [43]:
t7=torch.cat((t3,t6))
t7

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 10, 10],
        [10, 10, 10]])

In [44]:
#compute the sin of each elemnt

In [46]:
t8=torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [-0.5440, -0.5440, -0.5440],
        [-0.5440, -0.5440, -0.5440]])

In [48]:
t9=t8.reshape(2,2,3)
t9

tensor([[[ 0.8415,  0.9093,  0.1411],
         [-0.7568, -0.9589, -0.2794]],

        [[-0.5440, -0.5440, -0.5440],
         [-0.5440, -0.5440, -0.5440]]])

In [49]:
t9.shape

torch.Size([2, 2, 3])

Interoperability With Numpy

In [50]:
import numpy as np

In [51]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [52]:
x.shape

(2, 2)

In [54]:
#convert a numpy array into Tensor
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [56]:
x.dtype,y.dtype

(dtype('int32'), torch.int32)

In [57]:
#Convert Tensor into Numpy
z=y.numpy()
z

array([[1, 2],
       [3, 4]])

In [58]:
z.dtype

dtype('int32')

In [ ]:
#Why we need Pytorch since Numpy already provides data stractures. There are two main Reasons:
#1.Autograd
#2.GPU Supoort