# Linear Regression Using PyTorch

In [5]:
import torch.nn as nn
import numpy as np

In [6]:
#Input data(temp,rainfall,humidity)

In [9]:
inputs=np.array([[73,67,43],
                [91,88,64],
                [87,134,58],
                [102,43,37],
                [69,96,70],
                 [74,66,43],
                [91,87,65],
                [88,134,59],
                [101,44,37],
                [88,90,71],
                [73,66,44],
                [92,87,64],
                [87,135,57],
                [103,43,36],
                [68,97,70]],dtype='float32')

In [10]:
#Targets(apples,oranges)

In [11]:
targets=np.array([[56,70],
                 [81,101],
                 [119,133],
                 [22,37],
                 [103,119],
                 [57,69],
                 [80,102],
                 [118,132],
                 [21,38],
                 [104,118],
                 [57,69],
                 [82,100],
                 [118,134],
                 [20,38],
                 [102,120]],dtype='float32')

In [12]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [13]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 88.,  90.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [14]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [15]:
#we are using 15 training examples to illustrate how to work with large datasets in small batches 

Dataset and Dataloader

In [16]:
from torch.utils.data import TensorDataset

In [17]:
#defien dataset

In [18]:
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [19]:
#we also create Dataloader, which can split the data into batches of predefine size

In [20]:
from torch.utils.data import DataLoader

In [21]:
#define data loader

In [48]:
batch_sizes=5
train_dl=DataLoader(train_ds,batch_sizes,shuffle=True)

In [49]:
#we can use a data loader in a for loop

In [50]:
for xb,yb in train_dll:
    print(xb)
    print(yb)
    break 

tensor([[103.,  43.,  36.],
        [101.,  44.,  37.],
        [ 68.,  97.,  70.],
        [ 91.,  88.,  64.],
        [ 91.,  87.,  65.]])
tensor([[ 20.,  38.],
        [ 21.,  38.],
        [102., 120.],
        [ 81., 101.],
        [ 80., 102.]])


In [51]:
#Define Model

In [52]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3831,  0.3010, -0.5247],
        [ 0.3081, -0.1163,  0.2686]], requires_grad=True)
Parameter containing:
tensor([ 0.3501, -0.1179], requires_grad=True)


In [53]:
#Parameters

In [54]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3831,  0.3010, -0.5247],
         [ 0.3081, -0.1163,  0.2686]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3501, -0.1179], requires_grad=True)]

In [55]:
#Generate Prediction

In [56]:
preds=model(inputs)
preds

tensor([[25.9140, 26.1257],
        [28.1097, 34.8677],
        [43.5702, 26.6719],
        [32.9479, 36.2415],
        [18.9417, 28.7701],
        [25.9961, 26.5501],
        [27.2840, 35.2526],
        [43.4285, 27.2486],
        [32.8658, 35.8171],
        [23.8893, 35.5906],
        [25.0883, 26.5106],
        [28.1918, 35.2922],
        [44.3959, 26.2870],
        [33.8557, 36.2811],
        [18.8597, 28.3457]], grad_fn=<AddmmBackward0>)

In [57]:
#Loss Function

In [58]:
import torch.nn.functional as F

In [59]:
#Define loss function
loss_fn=F.mse_loss

In [60]:
loss=loss_fn(model(inputs),targets)

In [61]:
print(loss)

tensor(4154.7764, grad_fn=<MseLossBackward0>)


In [62]:
#Optimizer

In [63]:
#Define Optimizer

In [64]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [65]:
#Utility Function to train the model

In [71]:
def fit(num_epochs,model,loss_fn,opt,train_dl):
    #Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        #Train with the batches of data
        for xb,yb in train_dl:
            
            #1.Generate Prediction:
            pred=model(xb)
            
            #2.calculate loss
            loss=loss_fn(pred,yb)
            
            #3.compute gradients
            loss.backward()
            
            #4.update Parameters
            opt.step()
            
            #5.Reset the gradients to zero
            opt.zero_grad()
        #print the progress
        if (epoch+1)%100==0:
            print('Epoch [{}/{}], Loss:{:.4f}'.format(epoch+1,num_epochs,loss.item()))
            

In [72]:
fit(1000,model,loss_fn,opt,train_dl)

Epoch [100/1000], Loss:31.6852
Epoch [200/1000], Loss:54.3731
Epoch [300/1000], Loss:43.8820
Epoch [400/1000], Loss:33.7461
Epoch [500/1000], Loss:1.4311
Epoch [600/1000], Loss:3.4974
Epoch [700/1000], Loss:1.5242
Epoch [800/1000], Loss:3.3549
Epoch [900/1000], Loss:3.5615
Epoch [1000/1000], Loss:2.2434


In [73]:
#Genetrate Predictions Using the model
preds=model(inputs)
preds

tensor([[ 57.6578,  70.8546],
        [ 83.3801, 101.8244],
        [118.2555, 132.7030],
        [ 21.2934,  37.8067],
        [103.6875, 120.4248],
        [ 56.4197,  69.7815],
        [ 83.3200, 102.0172],
        [118.5996, 133.3639],
        [ 22.5314,  38.8798],
        [ 91.6004, 111.0170],
        [ 57.5976,  71.0474],
        [ 82.1421, 100.7513],
        [118.3156, 132.5102],
        [ 20.1154,  36.5408],
        [104.9256, 121.4979]], grad_fn=<AddmmBackward0>)

In [74]:
#compare with the targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [75]:
#Indeed, the predictions are quite close to our targets.

In [77]:
model(torch.tensor([[75.,63.,44.]]))

tensor([[54.3003, 68.1305]], grad_fn=<AddmmBackward0>)