In [1]:
import torch

In [2]:
#Create a Tensor

In [3]:
my_tensor=torch.tensor([[1,2,3],[4,5,6]])

In [4]:
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)

In [6]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
my_tensor=torch.tensor([[1,2,3],[4,5,6]],device='cpu',requires_grad=True,dtype=torch.float)#we can use cuda

In [8]:
device='cuda' if torch.cuda.is_available() else 'cpu'

In [9]:
my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float,device=device,requires_grad=True)#we can use cuda

In [10]:
my_tensor.dtype

torch.float32

In [11]:
my_tensor.device

device(type='cpu')

In [12]:
my_tensor.shape

torch.Size([2, 3])

In [13]:
my_tensor.requires_grad

True

In [14]:
#other common initialization methods

In [15]:
x=torch.empty(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x=torch.zeros((2,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
x=torch.rand((3,2))
x

tensor([[0.4423, 0.4684],
        [0.1389, 0.6057],
        [0.2408, 0.0935]])

In [18]:
x=torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
x=torch.eye(5,5)#I =eye
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
x=torch.arange(start=0,end=10,step=2)
x

tensor([0, 2, 4, 6, 8])

In [21]:
x=torch.linspace(start=0.1,end=1,steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [22]:
x=torch.empty(size=(1,5)).normal_(mean=0,std=1)
x

tensor([[ 1.6977, -0.5400, -1.6536,  2.0024,  0.7839]])

In [23]:
x=torch.empty(size=(1,5)).uniform_(0,1)
x

tensor([[0.2226, 0.1475, 0.2558, 0.8810, 0.4147]])

In [24]:
x=torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [25]:
#How to initialize and convert tensors to other types(int,float,double)

In [26]:
tensor=torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [27]:
tensor.bool()

tensor([False,  True,  True,  True])

In [28]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [29]:
tensor.long()#int 64

tensor([0, 1, 2, 3])

In [30]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [31]:
tensor.float()#float 32

tensor([0., 1., 2., 3.])

In [32]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [33]:
#Array to tensor conversation and vice-versa

In [34]:
import numpy as np

In [35]:
np_array=np.zeros(5)
np_array

array([0., 0., 0., 0., 0.])

In [36]:
tensor=torch.from_numpy(np_array)
tensor

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [37]:
np_array_back=tensor.numpy()
np_array_back

array([0., 0., 0., 0., 0.])

In [38]:
#tensor math and Compaasion operations

In [39]:
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])

In [40]:
x

tensor([1, 2, 3])

In [41]:
y

tensor([4, 5, 6])

In [42]:
#Addition

In [43]:
z1=torch.empty((3))
torch.add(x,y,out=z1)

tensor([5., 7., 9.])

In [44]:
z2=torch.add(x,y)

In [45]:
z2

tensor([5, 7, 9])

In [46]:
z3=x+y
z3

tensor([5, 7, 9])

In [47]:
#Subtraction

In [48]:
z=x-y

In [49]:
#Division

In [50]:
z4=torch.true_divide(x,y)


In [51]:
z4

tensor([0.2500, 0.4000, 0.5000])

In [52]:
#inplace operations

In [53]:
t=torch.zeros(3)
t

tensor([0., 0., 0.])

In [54]:
t.add_(x)

tensor([1., 2., 3.])

In [55]:
t+=x

In [56]:
t

tensor([2., 4., 6.])

In [57]:
#Exponentiation

In [58]:
z5=x.pow(2)

In [59]:
z5

tensor([1, 4, 9])

In [60]:
z=x**2

In [61]:
z

tensor([1, 4, 9])

In [62]:
z=x>0
z

tensor([True, True, True])

In [63]:
z=x<0
z

tensor([False, False, False])

In [64]:
#Matrix Multiplication

In [65]:
x1=torch.rand((2,5))

In [66]:
x1

tensor([[0.7591, 0.0584, 0.4813, 0.6242, 0.4046],
        [0.3111, 0.6159, 0.5884, 0.3590, 0.6598]])

In [67]:
x2=torch.rand((5,3))
x2

tensor([[0.9532, 0.7937, 0.4477],
        [0.8803, 0.2681, 0.1813],
        [0.4945, 0.7176, 0.7526],
        [0.3224, 0.5558, 0.5770],
        [0.2505, 0.6654, 0.3477]])

In [68]:
x3=torch.mm(x1,x2)
x3

tensor([[1.3156, 1.5797, 1.2135],
        [1.4107, 1.4728, 1.1303]])

In [69]:
x3=x1.mm(x2)

In [70]:
x3

tensor([[1.3156, 1.5797, 1.2135],
        [1.4107, 1.4728, 1.1303]])

In [71]:
#matrix exponentiation

In [72]:
matrix_exp=torch.rand((2,2))
matrix_exp

tensor([[0.3791, 0.0324],
        [0.1078, 0.8286]])

In [73]:
matrix_exp.matrix_power(3)

tensor([[0.0600, 0.0371],
        [0.1238, 0.5760]])

In [74]:
#Element wise multiplication

In [75]:
z=x*y

In [76]:
z

tensor([ 4, 10, 18])

In [77]:
#dot product

In [78]:
z=torch.dot(x,y)

In [79]:
z

tensor(32)

In [80]:
#batch Matrix Multiplication

In [81]:
batch=32
n=10
m=20
p=30

In [82]:
tensor1=torch.rand((batch,n,m))

In [83]:
tensor2=torch.rand((batch,m,p))

In [84]:
out_bmm=torch.bmm(tensor1,tensor2)

In [85]:
#Example of Broadcasting

In [86]:
x1=torch.rand((5,5))
x2=torch.rand((1,5))


In [87]:
z=x1-x2
z

tensor([[-0.5328, -0.0792,  0.1158, -0.3650,  0.0205],
        [-0.4289, -0.3533,  0.3818, -0.8491, -0.0047],
        [ 0.3351, -0.1454, -0.0045, -0.8000, -0.0541],
        [-0.4530, -0.9187,  0.5263, -0.0842,  0.4066],
        [ 0.2250, -0.6517,  0.7357, -0.3207,  0.2264]])

In [88]:
z=x1**x2
z

tensor([[0.2432, 0.9175, 0.8981, 0.5778, 0.7104],
        [0.3719, 0.6442, 0.9507, 0.0818, 0.6931],
        [0.9866, 0.8515, 0.8372, 0.1372, 0.6573],
        [0.3445, 0.0785, 0.9675, 0.8431, 0.9282],
        [0.9136, 0.3461, 0.9860, 0.6204, 0.8357]])

In [89]:
#Other useful tensor Operations


In [90]:
sum_x=torch.sum(x1,dim=0)
sum_x

tensor([2.3664, 2.8340, 2.0668, 2.1496, 2.7761])

In [91]:
vlaues,indices=torch.max(x1,dim=0)
vlaues

tensor([0.9793, 0.9173, 0.7981, 0.8296, 0.8429])

In [92]:
indices

tensor([2, 0, 4, 3, 3])

In [93]:
vlaues,indices=torch.min(x1,dim=0)


In [94]:
abs_x=torch.abs(x1)
abs_x

tensor([[0.1114, 0.9173, 0.1782, 0.5487, 0.4568],
        [0.2153, 0.6432, 0.4441, 0.0646, 0.4316],
        [0.9793, 0.8510, 0.0578, 0.1137, 0.3822],
        [0.1912, 0.0778, 0.5886, 0.8296, 0.8429],
        [0.8692, 0.3448, 0.7981, 0.5930, 0.6627]])

In [95]:
z=torch.argmax(x1,dim=0)
z

tensor([2, 0, 4, 3, 3])

In [96]:
z=torch.argmin(x1,dim=0)
z

tensor([0, 3, 2, 1, 2])

In [97]:
mean_x=torch.mean(x1,dim=0)
mean_x

tensor([0.4733, 0.5668, 0.4134, 0.4299, 0.5552])

In [98]:
z=torch.eq(x1,x2)#elemnet wise equal
z

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [99]:
x=torch.tensor([1,2,3])
x_sort=torch.sort(x,dim=0,descending=True)
x_sort

torch.return_types.sort(
values=tensor([3, 2, 1]),
indices=tensor([2, 1, 0]))

In [100]:
x_less_than_zero=torch.clamp(x,min=0)
x_less_than_zero

tensor([1, 2, 3])

In [101]:
x=torch.tensor([1,0,1,1,1],dtype=torch.bool)
x

tensor([ True, False,  True,  True,  True])

In [102]:
z=torch.any(x)#at least one of them should be True
z

tensor(True)

In [103]:
z=torch.all(x)#all of the value must be True
z

tensor(False)

In [104]:
#-------------------------Tensor Indexing----------------

In [105]:
batch_size=10
features=25
x=torch.rand((batch_size,features))

In [106]:
x[0]

tensor([0.8079, 0.6875, 0.5059, 0.0606, 0.4250, 0.9402, 0.1070, 0.7338, 0.9707,
        0.8466, 0.7573, 0.9679, 0.1331, 0.2070, 0.5538, 0.9589, 0.4065, 0.1637,
        0.4310, 0.5198, 0.5143, 0.7549, 0.2906, 0.1823, 0.6103])

In [107]:
x[0].shape

torch.Size([25])

In [108]:
x.shape

torch.Size([10, 25])

In [109]:
x[:,0]

tensor([0.8079, 0.5157, 0.8049, 0.9474, 0.3509, 0.1099, 0.5150, 0.8731, 0.6912,
        0.3647])

In [110]:
x[:,0].shape

torch.Size([10])

In [111]:
x[2,0:10]

tensor([0.8049, 0.4562, 0.1710, 0.5216, 0.6104, 0.0167, 0.7721, 0.8641, 0.9412,
        0.7751])

In [112]:
x[0,0]=100

In [113]:
#fancy indexing

In [114]:
x=torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
indices=[2,5,8]
indices

[2, 5, 8]

In [116]:
x[indices]

tensor([2, 5, 8])

In [117]:
x=torch.rand((3,5))
print(x)
rows=torch.tensor(([1,0]))
cols=torch.tensor(([4,0]))
x[rows,cols]

tensor([[0.1951, 0.2223, 0.7127, 0.8813, 0.1441],
        [0.3810, 0.0284, 0.1307, 0.3278, 0.3581],
        [0.8798, 0.5061, 0.0352, 0.7363, 0.1372]])


tensor([0.3581, 0.1951])

In [118]:
#more advanced indexing

In [119]:
x=torch.arange(10)
x[x<2]

tensor([0, 1])

In [120]:
x[x>5]

tensor([6, 7, 8, 9])

In [121]:
x[(x<2) | (x>7)]

tensor([0, 1, 8, 9])

In [122]:
x[(x>7) & (x<9)]

tensor([8])

In [123]:
x[x.remainder(2)==1]

tensor([1, 3, 5, 7, 9])

In [124]:
x[x.remainder(2)==0]

tensor([0, 2, 4, 6, 8])

In [125]:
x[x.remainder(1)==0]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
#Useful Operations

In [127]:
x


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
torch.where(x>5,x,x**2)

tensor([ 0,  1,  4,  9, 16, 25,  6,  7,  8,  9])

In [129]:
x=torch.tensor([0,1,1,2,2,3,3,4])
x

tensor([0, 1, 1, 2, 2, 3, 3, 4])

In [130]:
x.unique()

tensor([0, 1, 2, 3, 4])

In [131]:
x.ndimension()

1

In [132]:
x.numel()#count of number in tensor

8

In [133]:
#Tensor reshaping

In [134]:
x=torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [135]:
x_3x3=x.view(3,3)

In [136]:
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [137]:
x_3x3.shape

torch.Size([3, 3])

In [138]:
x1_3x3=x.reshape(3,3)
x1_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [139]:
y=x_3x3.t()#Transpose
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [141]:
y.contiguous().view(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [142]:
x1=torch.rand((2,5))
x2=torch.rand((2,5))

torch.cat((x1,x2),dim=0)

tensor([[0.2274, 0.9069, 0.3329, 0.7626, 0.3056],
        [0.6686, 0.2228, 0.6544, 0.8951, 0.6123],
        [0.7317, 0.3270, 0.3037, 0.8073, 0.2428],
        [0.6329, 0.8211, 0.2177, 0.1181, 0.0814]])

In [144]:
torch.cat((x1,x2),dim=0).shape

torch.Size([4, 5])

In [145]:
torch.cat((x1,x2),dim=1).shape

torch.Size([2, 10])

In [147]:
x1.view(-1)

tensor([0.2274, 0.9069, 0.3329, 0.7626, 0.3056, 0.6686, 0.2228, 0.6544, 0.8951,
        0.6123])

In [148]:
x1.view(-1).shape

torch.Size([10])

In [152]:
batch=8
x=torch.rand((batch,2,5))
z=x.view(batch,-1)
z

tensor([[0.8130, 0.1533, 0.3264, 0.5255, 0.5372, 0.5394, 0.8239, 0.8883, 0.6702,
         0.6778],
        [0.2266, 0.0210, 0.9263, 0.1437, 0.4857, 0.2326, 0.5392, 0.5486, 0.9784,
         0.0310],
        [0.5736, 0.4240, 0.9039, 0.4854, 0.4284, 0.6083, 0.9772, 0.2335, 0.6684,
         0.3911],
        [0.7678, 0.9890, 0.7752, 0.8812, 0.1098, 0.6951, 0.5487, 0.7633, 0.4159,
         0.6090],
        [0.6989, 0.6923, 0.1969, 0.0244, 0.7704, 0.1408, 0.9135, 0.5253, 0.4996,
         0.9780],
        [0.3615, 0.3060, 0.0918, 0.1093, 0.9378, 0.6521, 0.1003, 0.8813, 0.4564,
         0.6149],
        [0.4326, 0.7068, 0.9919, 0.2976, 0.7518, 0.3979, 0.9841, 0.9044, 0.6140,
         0.8067],
        [0.4561, 0.7204, 0.3570, 0.0530, 0.9627, 0.1586, 0.9858, 0.9732, 0.4884,
         0.1330]])

In [153]:
z.shape

torch.Size([8, 10])

In [154]:
z=x.permute(0,2,1)# to change axis 5 rows and 2 columns in 8 batches-->0 dimenstion zero , and other dimentions
z

tensor([[[0.8130, 0.5394],
         [0.1533, 0.8239],
         [0.3264, 0.8883],
         [0.5255, 0.6702],
         [0.5372, 0.6778]],

        [[0.2266, 0.2326],
         [0.0210, 0.5392],
         [0.9263, 0.5486],
         [0.1437, 0.9784],
         [0.4857, 0.0310]],

        [[0.5736, 0.6083],
         [0.4240, 0.9772],
         [0.9039, 0.2335],
         [0.4854, 0.6684],
         [0.4284, 0.3911]],

        [[0.7678, 0.6951],
         [0.9890, 0.5487],
         [0.7752, 0.7633],
         [0.8812, 0.4159],
         [0.1098, 0.6090]],

        [[0.6989, 0.1408],
         [0.6923, 0.9135],
         [0.1969, 0.5253],
         [0.0244, 0.4996],
         [0.7704, 0.9780]],

        [[0.3615, 0.6521],
         [0.3060, 0.1003],
         [0.0918, 0.8813],
         [0.1093, 0.4564],
         [0.9378, 0.6149]],

        [[0.4326, 0.3979],
         [0.7068, 0.9841],
         [0.9919, 0.9044],
         [0.2976, 0.6140],
         [0.7518, 0.8067]],

        [[0.4561, 0.1586],
         [0.72

In [155]:
z.shape

torch.Size([8, 5, 2])

In [156]:
x=torch.arange(10)

In [157]:
x.shape

torch.Size([10])

In [158]:
x.unsqueeze(0).shape

torch.Size([1, 10])

In [159]:
x.unsqueeze(0)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [160]:
x.unsqueeze(1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [161]:
x.unsqueeze(1).shape

torch.Size([10, 1])

In [163]:
x=torch.arange(10).unsqueeze(0).unsqueeze(1)
x

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [164]:
x.shape

torch.Size([1, 1, 10])

In [165]:
z=x.squeeze(1)
z

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [166]:
z.shape

torch.Size([1, 10])