# Linear Regression Using PyTorch

In [13]:
import torch
import torch.nn as nn
import numpy as np

In [14]:
#Input data(temp,rainfall,humidity)

In [15]:
inputs=np.array([[73,67,43],
                [91,88,64],
                [87,134,58],
                [102,43,37],
                [69,96,70],
                 [74,66,43],
                [91,87,65],
                [88,134,59],
                [101,44,37],
                [88,90,71],
                [73,66,44],
                [92,87,64],
                [87,135,57],
                [103,43,36],
                [68,97,70]],dtype='float32')

In [16]:
#Targets(apples,oranges)

In [17]:
targets=np.array([[56,70],
                 [81,101],
                 [119,133],
                 [22,37],
                 [103,119],
                 [57,69],
                 [80,102],
                 [118,132],
                 [21,38],
                 [104,118],
                 [57,69],
                 [82,100],
                 [118,134],
                 [20,38],
                 [102,120]],dtype='float32')

In [18]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [19]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 88.,  90.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [20]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [21]:
#we are using 15 training examples to illustrate how to work with large datasets in small batches 

Dataset and Dataloader

In [22]:
from torch.utils.data import TensorDataset

In [23]:
#defien dataset

In [24]:
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [25]:
#we also create Dataloader, which can split the data into batches of predefine size

In [26]:
from torch.utils.data import DataLoader

In [27]:
#define data loader

In [28]:
batch_sizes=5
train_dl=DataLoader(train_ds,batch_sizes,shuffle=True)

In [29]:
#we can use a data loader in a for loop

In [30]:
for xb,yb in train_dll:
    print(xb)
    print(yb)
    break 

NameError: name 'train_dll' is not defined

In [31]:
#Define Model

In [32]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3824, -0.4643,  0.1307],
        [-0.1964,  0.2641,  0.4567]], requires_grad=True)
Parameter containing:
tensor([-0.3382, -0.0082], requires_grad=True)


In [33]:
#Parameters

In [34]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3824, -0.4643,  0.1307],
         [-0.1964,  0.2641,  0.4567]], requires_grad=True),
 Parameter containing:
 tensor([-0.3382, -0.0082], requires_grad=True)]

In [35]:
#Generate Prediction

In [36]:
preds=model(inputs)
preds

tensor([[  2.0875,  22.9882],
        [  1.9650,  34.5898],
        [-21.7080,  44.7852],
        [ 23.5361,   8.2137],
        [ -9.3776,  43.7635],
        [  2.9342,  22.5277],
        [  2.5601,  34.7823],
        [-21.1949,  45.0455],
        [ 22.6894,   8.6742],
        [  0.8044,  38.9039],
        [  2.6826,  23.1808],
        [  2.8117,  34.1293],
        [-22.3030,  44.5927],
        [ 23.7878,   7.5607],
        [-10.2243,  44.2240]], grad_fn=<AddmmBackward0>)

In [37]:
#Loss Function

In [38]:
import torch.nn.functional as F

In [39]:
#Define loss function
loss_fn=F.mse_loss

In [40]:
loss=loss_fn(model(inputs),targets)

In [41]:
print(loss)

tensor(6179.7437, grad_fn=<MseLossBackward0>)


In [42]:
#Optimizer

In [43]:
#Define Optimizer

In [44]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [45]:
#Utility Function to train the model

In [46]:
def fit(num_epochs,model,loss_fn,opt,train_dl):
    #Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        #Train with the batches of data
        for xb,yb in train_dl:
            
            #1.Generate Prediction:
            pred=model(xb)
            
            #2.calculate loss
            loss=loss_fn(pred,yb)
            
            #3.compute gradients
            loss.backward()
            
            #4.update Parameters
            opt.step()
            
            #5.Reset the gradients to zero
            opt.zero_grad()
        #print the progress
        if (epoch+1)%100==0:
            print('Epoch [{}/{}], Loss:{:.4f}'.format(epoch+1,num_epochs,loss.item()))
            

In [47]:
fit(1000,model,loss_fn,opt,train_dl)

Epoch [100/1000], Loss:17.6322
Epoch [200/1000], Loss:1.0150
Epoch [300/1000], Loss:0.9273
Epoch [400/1000], Loss:2.1267
Epoch [500/1000], Loss:1.8438
Epoch [600/1000], Loss:1.1583
Epoch [700/1000], Loss:22.9141
Epoch [800/1000], Loss:21.9145
Epoch [900/1000], Loss:1.4915
Epoch [1000/1000], Loss:21.2844


In [48]:
#Genetrate Predictions Using the model
preds=model(inputs)
preds

tensor([[ 57.6135,  70.9653],
        [ 83.7902, 101.9530],
        [118.0084, 132.8009],
        [ 21.2628,  37.8949],
        [104.2378, 120.5782],
        [ 56.3844,  69.8919],
        [ 83.7729, 102.1483],
        [118.3841, 133.4630],
        [ 22.4919,  38.9683],
        [ 92.2227, 111.1608],
        [ 57.5962,  71.1605],
        [ 82.5611, 100.8796],
        [118.0257, 132.6057],
        [ 20.0510,  36.6263],
        [105.4669, 121.6516]], grad_fn=<AddmmBackward0>)

In [49]:
#compare with the targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [50]:
#Indeed, the predictions are quite close to our targets.

In [51]:
model(torch.tensor([[75.,63.,44.]]))

tensor([[54.3270, 68.2436]], grad_fn=<AddmmBackward0>)

In [52]:
#Create a model with more layers

In [54]:
model2=nn.Sequential(
nn.Linear(3,3),
nn.Sigmoid(),
nn.Linear(3,2))

In [58]:
opt=torch.optim.SGD(model2.parameters(),lr=1e-3)

In [59]:
fit(100,model2,F.mse_loss,opt,train_dl)

Epoch [100/100], Loss:1685.2542
